baseURL: "https://tiagosr.eu"
languageCode: "en-us"
title: "Tiago Silva Rodrigues"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: false
# disqusShortname: your-disqus-shortname
googleAnalytics: G-LGPMPKDSXP

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: notebook
      name: notebook
      title: Blog posts
      url: /notebook
      weight: 1
    - identifier: trainings
      name: Trainings
      title: My trainings
      url: /trainings
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Tiago Silva Rodrigues"
  description: This is me 
  # staticPath: ""  # The path to serve the static files from
  favicon: /content/images/favicon.png

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # Light Mode Color Preferences
  color:
    textColor: "#2d2f36"  # Dark Navy for text
    secondaryTextColor: "#4a5d70"  # Lighter Navy for secondary text
    backgroundColor: "#ffffff"  # White for background
    secondaryBackgroundColor: "#f0f2f5"  # Light Gray for secondary background
    primaryColor: "#27496d"  # Deep Navy Blue for primary elements
    secondaryColor: "#9ab3c2"  # Soft Blue for secondary elements

  # Dark Mode Color Preferences
  darkmode:
    textColor: "#ffffff"  # White for text
    secondaryTextColor: "#d0d2d6"  # Light Gray for secondary text
    backgroundColor: "#2d2f36"  # Dark Navy for background
    secondaryBackgroundColor: "#4a5d70"  # Lighter Navy for secondary background
    primaryColor: "#27496d"  # Deep Navy Blue for primary elements
    secondaryColor: "#c2ccd1"  # Soft Blue for secondary elements


  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Tiago S Rodrigues" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Tiago Silva Rodrigues"
    subtitle: "DevOps engineer"
    content: |
      As a dedicated DevOps professional, I specialize in the seamless integration of development and operational practices. My expertise lies in governance, leveraging Airflow for workflow automation, and implementing robust monitoring solutions. I am passionate about utilizing modern technologies to create efficient, reliable, and scalable systems. My goal is to ensure that every web application not only looks great and feels fantastic but also operates flawlessly under the hood.
    image: https://avatars.githubusercontent.com/u/36556000?v=4
    bottomImage:
      enable: true
    roundImage: true # Make hero image circular | default false
    # button:
    #   enable: true
    #   name: "Resume"
    #   # url: "#"
    #   download: true
    #   newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/TiagoSRodrigues
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/tiagosilvarodrigues

  # About
  about:
    enable: true
    title: "About Me"
    image: "https://media.licdn.com/dms/image/C5603AQFaNr8XTWeUGA/profile-displayphoto-shrink_800_800/0/1559701280006?e=1708560000&v=beta&t=PZG2-gSCZXay0S-_J9yE4O3yfNKjze6CNIOwSyxLZOA"
    content: |-
      With a unique blend of expertise in chemical engineering and software engineering, I bring a diverse set of technical and management skills to the IT industry. My journey has taken me to the heart of Cloud computing and DevOps at Novobanco, where my focus is on optimizing operational efficiency and maximizing client value through the adoption of industry best practices. 

      My role involves extensive work in project management, strategic planning, and problem-solving, where I consistently seek innovative solutions to complex challenges. I am passionate about professional development, always eager to learn and excel in dynamic, team-oriented settings.

      My vision is encapsulated in one phrase: "Generating Value." I am a strong advocate for developing intelligent processes, believing that they are crucial for building a better, more efficient society.

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Apache Airflow"
        - "OpenShift"
        - "CheckMK"
        - "Linux"
        - "Docker"
        - "GitHub"


  # Experience
  experience:
      enable: true
      items:
        - job: "Systems Analyst"
          company: "novobanco"
          date: "July 2022 - Present"
          content: "Current role focusing on DevOps, with tasks including API management and system monitoring."
        
        - job: "Application Analyst"
          company: "novobanco"
          date: "November 2020 - October 2022"
          content: "Worked in Cloud Computing Department, specializing in management and infrastructure."

        - job: "Production Technician"
          company: "Indorama Ventures"
          date: "November 2017 - October 2019"
          content: "Controlled industrial processes in the purification area of terephthalic acid."

        - job: "Operations Technician"
          company: "Artlant PTA"
          date: "December 2015 - October 2019"
          content: "Oversaw industrial process control and maintenance operations."

  # Education
  education:
    enable: true
    index: false
    items:
      - title: "Postgraduate, Software Engineering and Information Systems"
        school:
          name: "Instituto Superior Técnico"
        date: "2019 - 2020"
        content: |-
          Skills: Problem Solving, Microsoft SQL Server, Java, JavaScript, Microsoft Office

      - title: "Master's, Industrial Engineering and Management"
        school:
          name: "ISEL - Instituto Superior De Engenharia De Lisboa"
        date: "2018 - 2020"
        content: |-
          Skills: Problem Solving, Microsoft Office

      - title: "Bachelor's, Chemical Engineering"
        school:
          name: "ISEL - Instituto Superior De Engenharia De Lisboa"
        date: "2014 - 2018"
        content: |-
          Skills: Chemical Engineering, Microsoft Office

      - title: "Industrial Chemistry Course, Chemistry"
        school:
          name: "Escola Tecnológica do Litoral Alentejano"
        date: "2007 - 2010"

  # Achievements
  Achievements:
    enable: true
    title: "Trainings"
    items:
      - title: "Public Speaking"
        content: "Training in effective public speaking skills."
      - title: "DevOps Foundation"
        content: "Foundation training in DevOps principles and practices."
      - title: "Machine Learning with Python"
        content: "Certification in applying machine learning techniques using Python."
      - title: "DevOps with Docker & Kubernetes"
        content: "Specialized training in DevOps practices using Docker and Kubernetes."


  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Bullwhip simulator
        content: A supply chain simulator, with adjustable Bullwhip effective.
        featured:
          name: Code
          link: https://github.com/TiagoSRodrigues/Bullwhip
        badges:
          - "Supply chain management"
          - "python"
          - "Industrial management"
        links:
          - icon: fab fa-github
            url: https://github.com/TiagoSRodrigues/Bullwhip


      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: info@tiagosr.eu
    btnName: Mail me
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: xjvnbewq # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "notebook"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/TiagoSRodrigues
      linkedin: https://www.linkedin.com/in/tiagosilvarodrigues
      
  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"


  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>